import { Request, Response } from "express";

export const authStream = (req: Request, res: Response): void => {
  if (req.body.call == "publish") {
    try {
      //console.log("recieved key: ", req.body.name);
      // checkUserProfile(req.body).then((checker) => {
      //   if (checker == true) {
      //     console.log("ACCEPTED\n");
      //     res.sendStatus(201);
      //   } else {
      //     console.log("DECLINED\n");
      //     res.sendStatus(404);
      //   }
      // });
      res.sendStatus(201);
    } catch {
      console.log("An error occured");
      res.sendStatus(500);
    }
  } else {
    res.sendStatus(200); // Allow playback without auth
  }
};

// async function checkUserProfile(data: {
//   name: string;
//   pwd: string;
//   call: string;
// }) {
//   return db
//     .select("*")
//     .from("streamKeys")
//     .where({ streamKey: data.name })
//     .first()
//     .then((rows: any) => {
//       try {
//         if (rows.pwd == data.pwd) {
//           //.split("\0")[0] || rows.pwd == data.pwd) {
//           // Remove null characters generated by srtreplay
//           if (rows.start == null && rows.end == null) {
//             console.log("no date");
//             return true;
//           } else {
//             console.log(
//               "date now: ",
//               Date.now(),
//               " date start: ",
//               Date.parse(rows.start),
//               " date end: ",
//               Date.parse(rows.end)
//             );
//             if (rows.start !== null && rows.end !== null) {
//               if (
//                 Date.parse(rows.start) < Date.now() &&
//                 Date.parse(rows.end) > Date.now()
//               ) {
//                 return true;
//               } else {
//                 return false;
//               }
//             } else if (rows.start == null && rows.end !== null) {
//               if (Date.parse(rows.end) > Date.now()) {
//                 return true;
//               } else {
//                 return false;
//               }
//             } else if (rows.start !== null && rows.end == null) {
//               if (Date.parse(rows.start) < Date.now()) {
//                 return true;
//               } else {
//                 return false;
//               }
//             } else {
//               return false;
//             }
//           }
//         }
//         return false;
//       } catch {
//         return false;
//       }
//     });
// }
